name: Continous Deployment workflow

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      working-directory: ./07-Cloud
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Build
        run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Deploy
        run: npm run deploy
        working-directory: ${{env.working-directory}}
