name: Continous Deployment workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: cd .07-Cloud && npm install
      - name: Build
        run: cd .07-Cloud && npm run build
      - name: Deploy
        run: cd .07-Cloud && npm run deploy
